language: node_js
node_js:
- 6.10.1
before_script:
- npm install -g jasmine
- psql -c 'create database PostIt;' -U postgres
script:
- npm install
- npm run tests
after_script:
    - npm run coverage
after_success:
    - npm install -g codeclimate-test-reporter
    - codeclimate-test-reporter < coverage/lcov.info
env:
services:
  - postgresql