import express from 'express';
import userController from '../controllers/user';
import groupController from '../controllers/grup';
import groupMembersController from '../controllers/groupMember';
import groupPostsController from '../controllers/grouPost';
import loginController from '../controllers/login';
import auth from '../middlewares/auth';
import userValidator from '../middlewares/userValidation';
import groupMessagesController from '../controllers/groupMessages';
import groupValidator from '../middlewares/groupValidation';
import groupMembersValidation from '../middlewares/groupMembersValidation';

const app = express.Router();
app.get('/api/allUsers', auth, userController.allUsers);
app.post('/api/group', auth, groupValidator.groupValidation, groupController.create);
app.post('/api/user/signup', userValidator.basicValidation, userValidator.emailValidation, userController.create);
app.post('/api/group/:groupId/user',  auth, groupMembersValidation.isValidUser, groupMembersValidation.canAddUserToGroup, groupMembersValidation.isAmember, groupMembersController.create);
app.post('/api/group/:groupId/message', auth, groupValidator.getGroupInformationValidation, groupPostsController.create);
app.post('/api/user/signin', loginController.findUser);
app.get('/api/group/:groupId/messages', auth, groupValidator.getGroupInformationValidation, groupMessagesController.getPosts);
app.get('/api/user/:userId/groups', auth, userController.userGroups);
app.get('/api/group/:groupId/members', auth, groupValidator.getGroupInformationValidation, groupMembersController.getGroupmMembers);
app.get('/api/group/:groupId/nonMembers', auth, groupValidator.getGroupInformationValidation, groupMembersController.getNonGroupmMembers);
app.delete('/api/group/:groupId/delete', auth, groupValidator.deleteGroupValidation, groupController.Delete);
export default app;
