export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_CURRENT_USER_GROUPS = 'SET_CURRENT_USER_GROUPS';
export const SET_CURRENT_GROUP_MESSAGES = 'SET_CURRENT_GROUP_MESSAGES';
export const SET_CURRENT_GROUP = 'SET_CURRENT_GROUP';
