export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_CURRENT_USER_GROUPS = 'SET_CURRENT_USER_GROUPS';
export const SET_CURRENT_GROUP_MESSAGES = 'SET_CURRENT_GROUP_MESSAGES';
export const SET_CURRENT_GROUP = 'SET_CURRENT_GROUP';
export const SET_CURRENT_GROUP_MEMBERS = 'SET_CURRENT_GROUP_MEMBERS';
export const SET_ALL_USERS = 'SET_ALL_USERS';
